#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-Sensor-CO2-SCD30-PLUGGED_IN" id="HB-UNI-Sensor-CO2-SCD30-PLUGGED_IN" updatable="true">
DEVICE="HB-UNI-Sensor-CO2-SCD30-PLUGGED_IN"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="Sensor Kohlendioxid Netzbetrieb"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-uni-sensor-CO2-SCD30-plugged_in.png
DEVICE_THUMB=hb-uni-sensor-CO2-SCD30-plugged_in_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sensor-CO2-SCD30-plugged_in*.xml

#------------------------------------------------------------------------------
# Edit DEVDB.tcl
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Edit webui.js
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi


# ab hier von Jérôme, siehe https://homematic-forum.de/forum/viewtopic.php?f=76&t=60067
    

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="GENERIC|Sensortyp"
webuiInsertValue="stringTableHBCO2Sensor"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="GENERIC|Batteriespannung"
webuiInsertValue="stringTableHBBatteryVoltage"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="GENERIC|VCCSpannung"
webuiInsertValue="stringTableHBVCCVoltage"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="GENERIC|Akkumulatorspannung(ADC)"
webuiInsertValue="stringTableHBAccumulatorVoltage"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi



### Edit stringtable_de.txt ###

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deInsert="WEATHER|CO2\t\${stringTableHBCO2Sensor}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|CO2"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="WEATHER|OPERATING_VOLTAGE\t\${stringTableHBBatteryVoltage}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|OPERATING_VOLTAGE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deInsert="WEATHER|ACCUMULATOR_VOLTAGE\t\${stringTableHBAccumulatorVoltage}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|ACCUMULATOR_VOLTAGE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deInsert="WEATHER|VCC_VOLTAGE\t\${stringTableHBVCCVoltage}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|VCC_VOLTAGE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHBCO2Sensor\" : \"CO2 Messwert\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBCO2Sensor\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBBatteryVoltage\" : \"Batteriespannung\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBBatteryVoltage\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi


translate_deInsert="\n    \"stringTableHBAccumulatorVoltage\" : \"Akkumulatorspannung(ADC)\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBAccumulatorVoltage\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBVCCVoltage\" : \"VCC Spannung(ADC)\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBVCCVoltage\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

