#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-Sensor-TH-SHT75" id="HB-UNI-Sensor-TH-SHT75" updatable="true">
DEVICE="HB-UNI-Sensor-TH-SHT75"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="Sensor TH"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-uni-sensor-TH-SHT75.png
DEVICE_THUMB=hb-uni-sensor-TH-SHT75_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sensor-TH-SHT75*.xml

#------------------------------------------------------------------------------
# Edit DEVDB.tcl
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Edit webui.js
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi
    

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="GENERIC|Batteriespannung"
webuiInsertValue="stringTableHBBatteryVoltage"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="GENERIC|Rel. Luftfeuchtigkeit"
webuiInsertValue="stringTableHBHumidity"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi


### Edit stringtable_de.txt ###

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deInsert="WEATHER|OPERATING_VOLTAGE\t\${stringTableHBBatteryVoltage}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|OPERATING_VOLTAGE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="WEATHER|MY_HUMIDITY\t\${stringTableHBHumidity}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|MY_HUMIDITY"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi


### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","


translate_deInsert="\n    \"stringTableHBBatteryVoltage\" : \"Batteriespannung\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBBatteryVoltage\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBHumidity\" : \"Rel. Luftfeuchtigkeit\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBHumidity"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
