#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-Sensor-AQ-BME680_KF" id="HB-UNI-Sensor-AQ-BME680_KF">
DEVICE="HB-UNI-Sensor-AQ-BME680_KF"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="universeller Luftg\&uuml;tesensor"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-uni-sensor-AQ-BME680_KF.png
DEVICE_THUMB=hb-uni-sensor-AQ-BME680_KF_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sensor-AQ-BME680_KF*.xml

#------------------------------------------------------------------------------
# Undo DEVDB.tcl changes
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
        sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Undo webui.js changes
webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
        sed -i "/\($DEVICE\)/d" $webuiFile
fi
webuiSearch="GENERIC|Luftg%FCtegrad"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="GENERIC|Luftg%FCtegrad"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="GENERIC|Luftg%FCtelog10"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="GENERIC|Gaswiderstand"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="GENERIC|Gaswiderstand_min"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="GENERIC|Gaswiderstand_max"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="ALTITUDE_ABOVE_SEA_LEVEL"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="TRANSMIT_TIME_INTERVAL"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="GENERIC|Rel. Luftfeuchtigkeit"
sed -i "/\($webuiSearch\)/d" $webuiFile

#------------------------------------------------------------------------------
# remove device_xml links
rm -f $FIRMWARE_FILE

#------------------------------------------------------------------------------
# remove image files
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB


stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|AQ_LEVEL"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|AQ_LOG10"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|AQ_GAS_RESISTANCE_MIN"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|AQ_GAS_RESISTANCE_MAX"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|AQ_GAS_RESISTANCE_RAQ"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|OPERATING_VOLTAGE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="ALTITUDE_ABOVE_SEA_LEVEL"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="TRANSMIT_TIME_INTERVAL"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|MY_HUMIDITY"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile



translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBAirQualityLevel"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBAirQualityLog10"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile


translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBGasResistanceMin"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile


translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBGasResistanceMax"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile


translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBGasResistanceRaw"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile


translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBBatteryVoltage"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile


translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBAltitudeAboveSealevel"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile


translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBTransmitTimeIntervall"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBHumidity"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile


#------------------------------------------------------------------------------
# remove device_xml links
rm -f $FIRMWARE_FILE

#------------------------------------------------------------------------------
# remove image files
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB


