#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-CO2-SCD30" id="HB-UNI-Sensor-CO2-SCD30">
DEVICE="HB-UNI-Sensor-CO2-SCD30"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="Sensor Kohlendioxid"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-uni-sensor-CO2-SCD30.png
DEVICE_THUMB=hb-uni-sensor-CO2-SCD30_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sensor-CO2*.xml

#------------------------------------------------------------------------------
# Undo DEVDB.tcl changes
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
        sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Undo webui.js changes
webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
        sed -i "/\($DEVICE\)/d" $webuiFile
fi
webuiSearch="GENERIC|Sensortyp"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="GENERIC|Batteriespannung"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="GENERIC|VCCSpannung"
sed -i "/\($webuiSearch\)/d" $webuiFile

#------------------------------------------------------------------------------
# remove device_xml links
rm -f $FIRMWARE_FILE

#------------------------------------------------------------------------------
# remove image files
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|CO2"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|OPERATING_VOLTAGE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|VCC_VOLTAGE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|ACCUMULATOR_VOLTAGE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile


translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBCO2Sensor"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBBatteryVoltage"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBVCCVoltage"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBAccumulatorVoltage"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

#------------------------------------------------------------------------------
# remove device_xml links
rm -f $FIRMWARE_FILE

#------------------------------------------------------------------------------
# remove image files
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

