#!/bin/sh

# remove two orphans of hb-ep-devices-addon V1.6 (missing in the concerning uninstall scripts)

webuiFile="/www/webui/webui.js"


webuiSearch="GENERIC|Taupunkt"
sed -i "/\($webuiSearch\)/d" $webuiFile

webuiSearch="GENERIC|Akkumulatorspannung(ADC)"
sed -i "/\($webuiSearch\)/d" $webuiFile
