M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu22.04.1} date 2024-09-27T18:44:30+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-27T18:44:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1039
%
G90
G05
T1
X0.399Y2.0632
X0.871Y0.2333
M30
