M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu22.04.1} date Sa 13 Jan 2024 12:35:50 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-13T12:35:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1039
%
G90
G05
T1
X0.399Y2.0632
X0.871Y0.2333
T0
M30
